version: '3'
services:
  app:
    build: ./app
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: always
    depends_on:
      - api
    environment:
      NODE_ENV: ${ENV}
    tty: true
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    restart: always
    depends_on:
      - db
    environment:
      NODE_ENV: ${ENV}
    tty: true
  db:
    image: mongo
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}